repos:
  - repo: https://github.com/psf/black
    rev: 23.10.1
    hooks:
      - id: black
        args: ["--target-version", "py311"]
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        args: [--prose-wrap=preserve, --print-width=90]
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
